
DELETE http://localhost:3001/api/persons/689cb65d9ef0b54b420e8bd0

###
GET  http://localhost:3001/api/persons

###
POST http://localhost:3001/api/persons HTTP/1.1
Content-Type: application/json

{
    "name": "shirley",
    "number": "192384672534"
}